### ISSUE TITLE
pprof is not working

### ISSUE THREAD

**Issue by momox-maxim** [arnaud-lb/php-memory-profiler#89] opened 2023-06-06 08:19 UTC
### Description

Hello,
I have tried the following code:

```bash
pprof --web memprofoutputgrind1501897
pprof --gv memprofoutputgrind1501897
```

Resulted in this output:
```
root@598c0e0bc2ca:/var/www# pprof --web memprofoutputgrind1501897
memprofoutputgrind1501897: parsing profile: unrecognized profile format
pprof: failed to fetch any source profiles
root@598c0e0bc2ca:/var/www# pprof --gv memprofoutputgrind1501897
memprofoutputgrind1501897: parsing profile: unrecognized profile format
pprof: failed to fetch any source profiles
```

But I expected this output instead:
as from the README.md in https://github.com/arnaud-lb/php-memory-profiler#memprof_dump_pprofresource-stream

### php-memprof Version

3.0.2 

### PHP Version

PHP 8.2.3 (cli)

### Operating System
docker

**Comment by arnaud-lb** [comment] 2023-09-02 13:10
Duplicate of https://github.com/arnaud-lb/php-memory-profiler/issues/83

**Closed as not planned by arnaud-lb** 2023-09-02 13:10 UTC
Labels: bug
